import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/global.css";
import "@/styles/cookies.css";
import "swiper/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    utag_data: any;
    tealium_data2track: any;
    utag: any;
    TealiumConsentPrivacyLink: () => void;
    grecaptcha: { reset: () => void };
  }
}

const Nexa = localFont({
  src: [
    {
      path: "../../styles/fonts/Nexa-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../styles/fonts/Nexa-Book.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../styles/fonts/Nexa-Bold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../styles/fonts/Nexa-XBold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../styles/fonts/Nexa-Heavy.woff2",
      style: "normal",
      weight: "800",
    },
  ],
  variable: "--nexa",
});

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  return (
    <html lang={lang}>
      <head>
        {/* <Script src={`/gaScript.js`} defer /> */}
        {/* <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-6JGDZBP4T1"
        /> */}
      </head>
      <body className={`${Nexa.variable} ${Nexa.className}`}>
        {/* GTM Script */}
        {/* <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-T3PRNZWF"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          ></iframe>
        </noscript> */}

        {children}
      </body>
    </html>
  );
}
